---
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: check-added-large-files
    - id: detect-private-key
    - id: no-commit-to-branch
      args: ['--branch', 'main']
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    #- id: go-vet
    #- id: go-lint
    #- id: go-imports
    #- id: go-cyclo
    #  args: [-over=15]
    #- id: validate-toml
    - id: no-go-testing
    #- id: gometalinter
    - id: golangci-lint
    #- id: go-critic
    #- id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
