---
# REVIEW https://github.com/dexidp/dex/blob/5807011b6a1e203bae714e6e9f2cb632783ae091/.github/workflows/release.yml#L43

name: Docker build on push
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  #ACTIONS_ALLOW_UNSECURE_COMMAND: true

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build and push all the stuff defined in this repo
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set env variables
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
        echo "SHORTSHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "DOCKER_HUB_REPO=sats-stacker" >> $GITHUB_ENV


    - name: Show set env variables
      run: |
        printf "    BRANCH: %s\n"  "$BRANCH"
        printf "    SHORTSHA: %s\n"  "$SHORTSHA"
        printf "    REPO: %s\n" "$GITHUB_REPOSITORY"
        printf "    COMMIT ID: %s\n" "$GITHUB_SHA"
        printf "    DOCKER REPO: %s\n" "$DOCKER_HUB_REPO"
        printf "    GITHUB_ACTOR: %s\n" "$GITHUB_ACTOR"
        printf "    GITHUB_REPOSITORY: %s\n" "$GITHUB_REPOSITORY"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Setup Docker buildx action
      uses: crazy-max/ghaction-docker-buildx@v1
      id: buildx
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Show available Docker buildx platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build against master
      run: |
        docker buildx build \
        --cache-from "type=local,src=/tmp/.buildx-cache" \
        --cache-to "type=local,dest=/tmp/.buildx-cache" \
        --platform linux/arm64,linux/amd64,linux/arm/v7 \
        --tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_HUB_REPO:master-$SHORTSHA \
        --output "type=registry" .

    - name: Build against latest tag
      run: |
        docker buildx build \
        --cache-from "type=local,src=/tmp/.buildx-cache" \
        --cache-to "type=local,dest=/tmp/.buildx-cache" \
        --platform linux/arm64,linux/amd64,linux/arm/v7 \
        --tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_HUB_REPO:latest \
        --output "type=registry" .
