name: Docker build on tag
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  #ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  TAG_FMT: ^refs/tags/(((.?[0-9]+){3,4}))$

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build Sats Stacker
    steps:

    - name: Setup Environment
      run: |
        echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        echo "DOCKER_HUB_REPO=sats-stacker" >> $GITHUB_ENV

    - name: Show set environment variables
      run: |
        printf "    TAG: %s\n"  "$TAG"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Checkout project
      uses: actions/checkout@v2

    - name: Setup Docker buildx action
      uses: crazy-max/ghaction-docker-buildx@v1
      id: buildx
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Show available Docker buildx platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Run Docker buildx against the tag
      run: |
        docker buildx build \
        --cache-from "type=local,src=/tmp/.buildx-cache" \
        --cache-to "type=local,dest=/tmp/.buildx-cache" \
        --platform linux/amd64,linux/arm64,linux/arm/v7 \
        --tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_HUB_REPO:$TAG \
        --output "type=local,dest=output" \
        --output "type=registry" .

    - name: build against latest
      run: |
        docker buildx build \
        --cache-from "type=local,src=/tmp/.buildx-cache" \
        --cache-to "type=local,dest=/tmp/.buildx-cache" \
        --platform linux/amd64,linux/arm64,linux/arm/v7 \
        --tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_HUB_REPO:latest \
        --output "type=registry" .

    - name: Rename Files for release on github
      run: |
        mv output/linux_arm_v7/sats-stacker output/sats-stacker_armv7
        chmod a+x ./output/sats-stacker_armv7
        mv output/linux_arm64/sats-stacker output/sats-stacker_arm64
        chmod a+x ./output/sats-stacker_arm64
        mv output/linux_amd64/sats-stacker output/sats-stacker_amd64
        chmod a+x ./output/sats-stacker_amd64
        rm -rf output/linux_arm_v7 output/linux_arm64 output/linux_amd64

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          output/sats-stacker_armv7
          output/sats-stacker_arm64
          output/sats-stacker_amd64
        body_path: ${{ github.workflow }}-CHANGELOG.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
